local L = LibStub("AceLocale-3.0"):NewLocale("GCD", "enUS")
if not L then return end

L["Add Spell"] = true
L["All specified colors are vertex colors! (see wowwiki.com)"] = true
L["All unlockable modules are disabled!"] = true
L["Attach to cursor"] = true
L["Auto arrange icons"] = true
L["Background"] = true
L["Bar"] = true
L["Border"] = true
L["Bottom"] = true
L["Bottom has to be a number!"] = true
L["Cast color"] = true
L["Casttime"] = true
L["Color"] = true
L["Colors"] = true
L["Display"] = true
L["Enabled"] = true
L["Font"] = true
L["Font Size"] = true
L["General"] = true
L["Hide default castbar"] = true
L["Horizontal Offset"] = true
L["Icon size"] = true
L["Latency color"] = true
L["Left"] = true
L["Left has to be a number!"] = true
L["Miscellaneous"] = true
L["Position"] = true
L["Primary"] = true
L["Radius"] = true
L["Remove Spell"] = true
L["Restore defaults"] = true
L["Ring"] = true
L["Rotate"] = true
L["Secondary"] = true
L["Show spark only"] = true
L["Spark"] = true
L["Spellcds"] = true
L["Spells"] = true
L["Spell Text"] = true
L["Talent Specs"] = true
L["Text"] = true
L["Texture"] = true
L["Thickness"] = true
L["Unlock"] = true
L["Vertical Offset"] = true
L["x-Offset"] = true
L["y-Offset"] = true

