local L = LibStub("AceLocale-3.0"):NewLocale("GCD", "koKR")
if not L then return end

L["Add Spell"] = "주문 추가"
L["All specified colors are vertex colors! (see wowwiki.com)"] = " All specified colors are vertex colors! (see wowwiki.com)"
L["All unlockable modules are disabled!"] = "All unlockable modules are disabled!" -- Requires localization
L["Attach to cursor"] = "커서에 붙이기"
L["Auto arrange icons"] = "자동 아이콘 정렬"
L["Background"] = "배경"
L["Bar"] = "Bar"
L["Border"] = "경계"
L["Bottom"] = "바닥"
L["Bottom has to be a number!"] = "Bottom has to be a number!" -- Requires localization
L["Cast color"] = "시전 색상"
L["Casttime"] = "시전시간"
L["Color"] = "색상"
L["Colors"] = "색상"
L["Display"] = "표시"
L["Enabled"] = "사용"
L["Font"] = "폰트"
L["Font Size"] = "폰트 크기"
L["General"] = "General" -- Requires localization
L["Hide default castbar"] = "기본 시전바 숨기기"
L["Horizontal Offset"] = "Horizontal Offset" -- Requires localization
L["Icon size"] = "Icon size" -- Requires localization
L["Latency color"] = "지연 색상"
L["Left"] = "왼쪽"
L["Left has to be a number!"] = "Left has to be a number!" -- Requires localization
L["Miscellaneous"] = "기타"
L["Position"] = "위치"
L["Primary"] = "Primary" -- Requires localization
L["Radius"] = "반지름"
L["Remove Spell"] = "주문 제거"
L["Restore defaults"] = "기본값 복구"
L["Ring"] = "Ring" -- Requires localization
L["Rotate"] = "회전"
L["Secondary"] = "Secondary" -- Requires localization
L["Show spark only"] = "Show spark only" -- Requires localization
L["Spark"] = "Spark" -- Requires localization
L["Spellcds"] = "Spellcds" -- Requires localization
L["Spells"] = "주문"
L["Spell Text"] = "주문명"
L["Talent Specs"] = "특성 스펙"
L["Text"] = "텍스트"
L["Texture"] = "텍스쳐"
L["Thickness"] = "Thickness" -- Requires localization
L["Unlock"] = "잠금 해제"
L["Vertical Offset"] = "Vertical Offset" -- Requires localization
L["x-Offset"] = "x축"
L["y-Offset"] = "y축"
