local L = LibStub("AceLocale-3.0"):NewLocale("GCD", "ruRU")
if not L then return end

L["Add Spell"] = "Add Spell" -- Requires localization
L["All specified colors are vertex colors! (see wowwiki.com)"] = "All specified colors are vertex colors! (see wowwiki.com)" -- Requires localization
L["All unlockable modules are disabled!"] = "All unlockable modules are disabled!" -- Requires localization
L["Attach to cursor"] = "Attach to cursor" -- Requires localization
L["Auto arrange icons"] = "Auto arrange icons" -- Requires localization
L["Background"] = "Background" -- Requires localization
L["Bar"] = "Bar" -- Requires localization
L["Border"] = "Border" -- Requires localization
L["Bottom"] = "Bottom" -- Requires localization
L["Bottom has to be a number!"] = "Bottom has to be a number!" -- Requires localization
L["Cast color"] = "Цвет применения заклинания" -- Needs review
L["Casttime"] = "Время применения" -- Needs review
L["Color"] = "Цвет" -- Needs review
L["Colors"] = "Colors" -- Requires localization
L["Display"] = "Display" -- Requires localization
L["Enabled"] = "Включить" -- Needs review
L["Font"] = "Font" -- Requires localization
L["Font Size"] = "Font Size" -- Requires localization
L["General"] = "General" -- Requires localization
L["Hide default castbar"] = "Hide default castbar" -- Requires localization
L["Horizontal Offset"] = "Horizontal Offset" -- Requires localization
L["Icon size"] = "Icon size" -- Requires localization
L["Latency color"] = "Цвет задержки" -- Needs review
L["Left"] = "Left" -- Requires localization
L["Left has to be a number!"] = "Left has to be a number!" -- Requires localization
L["Miscellaneous"] = "Miscellaneous" -- Requires localization
L["Position"] = "Position" -- Requires localization
L["Primary"] = "Primary" -- Requires localization
L["Radius"] = "Radius" -- Requires localization
L["Remove Spell"] = "Remove Spell" -- Requires localization
L["Restore defaults"] = "Restore defaults" -- Requires localization
L["Ring"] = "Кольцо" -- Needs review
L["Rotate"] = "Rotate" -- Requires localization
L["Secondary"] = "Secondary" -- Requires localization
L["Show spark only"] = "Show spark only" -- Requires localization
L["Spark"] = "Искра" -- Needs review
L["Spellcds"] = "Восстановление заклинаний" -- Needs review
L["Spells"] = "Spells" -- Requires localization
L["Spell Text"] = "Spell Text" -- Requires localization
L["Talent Specs"] = "Talent Specs" -- Requires localization
L["Text"] = "Text" -- Requires localization
L["Texture"] = "Текстура" -- Needs review
L["Thickness"] = "Thickness" -- Requires localization
L["Unlock"] = "Unlock" -- Requires localization
L["Vertical Offset"] = "Vertical Offset" -- Requires localization
L["x-Offset"] = "x-Offset" -- Requires localization
L["y-Offset"] = "y-Offset" -- Requires localization
