local L = LibStub("AceLocale-3.0"):NewLocale("GCD", "zhTW")
if not L then return end

L["Add Spell"] = "增加法術"
L["All specified colors are vertex colors! (see wowwiki.com)"] = "請注意所有的特定顏色都是頂點色" -- Needs review
L["All unlockable modules are disabled!"] = "所有可解鎖的模塊已禁用!"
L["Attach to cursor"] = "吸附到光標"
L["Auto arrange icons"] = "自動調整圖像"
L["Background"] = "背景"
L["Bar"] = "Bar" -- Requires localization
L["Border"] = "Border" -- Requires localization
L["Bottom"] = "底部"
L["Bottom has to be a number!"] = "底部應當為一個數字!"
L["Cast color"] = "施法顏色" -- Needs review
L["Casttime"] = "施法時間"
L["Color"] = "顏色" -- Needs review
L["Colors"] = "顏色"
L["Display"] = "顯示"
L["Enabled"] = "啟用" -- Needs review
L["Font"] = "字型"
L["Font Size"] = "字型大小"
L["General"] = "一般"
L["Hide default castbar"] = "隱藏預設施法條"
L["Horizontal Offset"] = "Horizontal Offset" -- Requires localization
L["Icon size"] = "圖像尺寸"
L["Latency color"] = "延遲顏色" -- Needs review
L["Left"] = "左邊"
L["Left has to be a number!"] = "左邊應當為一個數字!"
L["Miscellaneous"] = "雜項"
L["Position"] = "位置"
L["Primary"] = "首要"
L["Radius"] = "Radius" -- Requires localization
L["Remove Spell"] = "移除法術"
L["Restore defaults"] = "恢復預設"
L["Ring"] = "環樣式" -- Needs review
L["Rotate"] = "旋轉" -- Needs review
L["Secondary"] = "次要"
L["Show spark only"] = "Show spark only" -- Requires localization
L["Spark"] = "閃光樣式" -- Needs review
L["Spellcds"] = "法術冷卻" -- Needs review
L["Spells"] = "法術"
L["Spell Text"] = "法術文字"
L["Talent Specs"] = "天賦"
L["Text"] = "本文"
L["Texture"] = "材質" -- Needs review
L["Thickness"] = "Thickness" -- Requires localization
L["Unlock"] = "解鎖"
L["Vertical Offset"] = "Vertical Offset" -- Requires localization
L["x-Offset"] = "X-偏移"
L["y-Offset"] = "Y-偏移"
