local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "dsmbg1", [[Interface\Addons\SharedMedia_MyMedia\background\dsmbg1.tga]]) 
LSM:Register("background", "dsmbg2", [[Interface\Addons\SharedMedia_MyMedia\background\dsmbg2.tga]]) 
LSM:Register("background", "dsmbg3", [[Interface\Addons\SharedMedia_MyMedia\background\dsmbg3.tga]]) 
LSM:Register("background", "DsmOpaqueV1", [[Interface\Addons\SharedMedia_MyMedia\background\DsmOpaqueV1.tga]]) 
LSM:Register("background", "DsmOpaqueV2", [[Interface\Addons\SharedMedia_MyMedia\background\DsmOpaqueV2.tga]]) 
LSM:Register("background", "DsmOpaqueV4", [[Interface\Addons\SharedMedia_MyMedia\background\DsmOpaqueV4.tga]]) 
LSM:Register("background", "DsmV4", [[Interface\Addons\SharedMedia_MyMedia\background\DsmV4.tga]]) 
LSM:Register("background", "DsmV5", [[Interface\Addons\SharedMedia_MyMedia\background\DsmV5.tga]]) 
LSM:Register("background", "DsmV6", [[Interface\Addons\SharedMedia_MyMedia\background\DsmV6.tga]]) 
LSM:Register("background", "DsmV7", [[Interface\Addons\SharedMedia_MyMedia\background\DsmV7.tga]]) 
LSM:Register("background", "DsmV8", [[Interface\Addons\SharedMedia_MyMedia\background\DsmV8.tga]]) 
LSM:Register("background", "DsmV9", [[Interface\Addons\SharedMedia_MyMedia\background\DsmV9.tga]]) 
LSM:Register("background", "HalBackground", [[Interface\Addons\SharedMedia_MyMedia\background\HalBackground.tga]]) 
LSM:Register("background", "HalBackgroundA", [[Interface\Addons\SharedMedia_MyMedia\background\HalBackgroundA.tga]]) 
LSM:Register("background", "HalE", [[Interface\Addons\SharedMedia_MyMedia\background\HalE.tga]]) 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "1", [[Interface\Addons\SharedMedia_MyMedia\border\1.tga]]) 
LSM:Register("border", "2", [[Interface\Addons\SharedMedia_MyMedia\border\2.tga]]) 
LSM:Register("border", "3", [[Interface\Addons\SharedMedia_MyMedia\border\3.tga]]) 
LSM:Register("border", "4", [[Interface\Addons\SharedMedia_MyMedia\border\4.tga]]) 
LSM:Register("border", "5", [[Interface\Addons\SharedMedia_MyMedia\border\5.tga]]) 
LSM:Register("border", "6", [[Interface\Addons\SharedMedia_MyMedia\border\6.tga]]) 
LSM:Register("border", "BorderPlain2", [[Interface\Addons\SharedMedia_MyMedia\border\BorderPlain2.tga]]) 
LSM:Register("border", "BorderTexture", [[Interface\Addons\SharedMedia_MyMedia\border\BorderTexture.tga]]) 
LSM:Register("border", "Caith2", [[Interface\Addons\SharedMedia_MyMedia\border\Caith2.tga]]) 
LSM:Register("border", "CaithThin", [[Interface\Addons\SharedMedia_MyMedia\border\CaithThin.tga]]) 
LSM:Register("border", "dsmbd1", [[Interface\Addons\SharedMedia_MyMedia\border\dsmbd1.tga]]) 
LSM:Register("border", "dsmbd2", [[Interface\Addons\SharedMedia_MyMedia\border\dsmbd2.tga]]) 
LSM:Register("border", "dsmbd3", [[Interface\Addons\SharedMedia_MyMedia\border\dsmbd3.tga]]) 
LSM:Register("border", "dsmbd4", [[Interface\Addons\SharedMedia_MyMedia\border\dsmbd4.tga]]) 
LSM:Register("border", "dsmbd5", [[Interface\Addons\SharedMedia_MyMedia\border\dsmbd5.tga]]) 
LSM:Register("border", "dsmbd6", [[Interface\Addons\SharedMedia_MyMedia\border\dsmbd6.tga]]) 
LSM:Register("border", "HalBorder", [[Interface\Addons\SharedMedia_MyMedia\border\HalBorder.tga]]) 
LSM:Register("border", "IshBorder", [[Interface\Addons\SharedMedia_MyMedia\border\IshBorder.tga]]) 
LSM:Register("border", "roth", [[Interface\Addons\SharedMedia_MyMedia\border\roth.tga]]) 
LSM:Register("border", "Rothborder", [[Interface\Addons\SharedMedia_MyMedia\border\Rothborder.tga]]) 
LSM:Register("border", "Stripped", [[Interface\Addons\SharedMedia_MyMedia\border\Stripped.tga]]) 

-- -----
--   FONT
-- -----
LSM:Register("font", "04B_03B_", [[Interface\Addons\SharedMedia_MyMedia\font\04B_03B_.TTF]]) 
LSM:Register("font", "04B_03__", [[Interface\Addons\SharedMedia_MyMedia\font\04B_03__.TTF]]) 
LSM:Register("font", "04B_08__", [[Interface\Addons\SharedMedia_MyMedia\font\04B_08__.TTF]]) 
LSM:Register("font", "04B_20__", [[Interface\Addons\SharedMedia_MyMedia\font\04B_20__.TTF]]) 
LSM:Register("font", "04B_24__", [[Interface\Addons\SharedMedia_MyMedia\font\04B_24__.TTF]]) 
LSM:Register("font", "04B_25__", [[Interface\Addons\SharedMedia_MyMedia\font\04B_25__.TTF]]) 
LSM:Register("font", "04B_31__", [[Interface\Addons\SharedMedia_MyMedia\font\04B_31__.TTF]]) 
LSM:Register("font", "28", [[Interface\Addons\SharedMedia_MyMedia\font\28.ttf]]) 
LSM:Register("font", "5P5", [[Interface\Addons\SharedMedia_MyMedia\font\5P5.ttf]]) 
LSM:Register("font", "5square", [[Interface\Addons\SharedMedia_MyMedia\font\5square.ttf]]) 
LSM:Register("font", "ABF", [[Interface\Addons\SharedMedia_MyMedia\font\ABF.ttf]]) 
LSM:Register("font", "accid___", [[Interface\Addons\SharedMedia_MyMedia\font\accid___.ttf]]) 
LSM:Register("font", "Adventure", [[Interface\Addons\SharedMedia_MyMedia\font\Adventure.ttf]]) 
LSM:Register("font", "AGENCYB", [[Interface\Addons\SharedMedia_MyMedia\font\AGENCYB.TTF]]) 
LSM:Register("font", "AGENCYR", [[Interface\Addons\SharedMedia_MyMedia\font\AGENCYR.TTF]]) 
LSM:Register("font", "ambitsek", [[Interface\Addons\SharedMedia_MyMedia\font\ambitsek.ttf]]) 
LSM:Register("font", "avantgarde", [[Interface\Addons\SharedMedia_MyMedia\font\avantgarde.ttf]]) 
LSM:Register("font", "Avanti", [[Interface\Addons\SharedMedia_MyMedia\font\Avanti.ttf]]) 
LSM:Register("font", "Avenir LT 55 Roman", [[Interface\Addons\SharedMedia_MyMedia\font\Avenir LT 55 Roman.ttf]]) 
LSM:Register("font", "Avenir LT 85 Heavy", [[Interface\Addons\SharedMedia_MyMedia\font\Avenir LT 85 Heavy.ttf]]) 
LSM:Register("font", "Avqest", [[Interface\Addons\SharedMedia_MyMedia\font\Avqest.ttf]]) 
LSM:Register("font", "Base", [[Interface\Addons\SharedMedia_MyMedia\font\Base.ttf]]) 
LSM:Register("font", "Bazooka", [[Interface\Addons\SharedMedia_MyMedia\font\Bazooka.ttf]]) 
LSM:Register("font", "BigNoodleTitling-Oblique", [[Interface\Addons\SharedMedia_MyMedia\font\BigNoodleTitling-Oblique.ttf]]) 
LSM:Register("font", "BigNoodleTitling", [[Interface\Addons\SharedMedia_MyMedia\font\BigNoodleTitling.ttf]]) 
LSM:Register("font", "bitdust2", [[Interface\Addons\SharedMedia_MyMedia\font\bitdust2.ttf]]) 
LSM:Register("font", "BlackChancery", [[Interface\Addons\SharedMedia_MyMedia\font\BlackChancery.ttf]]) 
LSM:Register("font", "BLUEHIGD", [[Interface\Addons\SharedMedia_MyMedia\font\BLUEHIGD.TTF]]) 
LSM:Register("font", "BMbug", [[Interface\Addons\SharedMedia_MyMedia\font\BMbug.TTF]]) 
LSM:Register("font", "BMcinema", [[Interface\Addons\SharedMedia_MyMedia\font\BMcinema.TTF]]) 
LSM:Register("font", "BMdelicoA16", [[Interface\Addons\SharedMedia_MyMedia\font\BMdelicoA16.ttf]]) 
LSM:Register("font", "bmf00", [[Interface\Addons\SharedMedia_MyMedia\font\bmf00.ttf]]) 
LSM:Register("font", "bmf10", [[Interface\Addons\SharedMedia_MyMedia\font\bmf10.ttf]]) 
LSM:Register("font", "bmf20", [[Interface\Addons\SharedMedia_MyMedia\font\bmf20.ttf]]) 
LSM:Register("font", "bmf_00", [[Interface\Addons\SharedMedia_MyMedia\font\bmf_00.ttf]]) 
LSM:Register("font", "bmf_10", [[Interface\Addons\SharedMedia_MyMedia\font\bmf_10.ttf]]) 
LSM:Register("font", "bmf_20", [[Interface\Addons\SharedMedia_MyMedia\font\bmf_20.ttf]]) 
LSM:Register("font", "BMmicro7", [[Interface\Addons\SharedMedia_MyMedia\font\BMmicro7.TTF]]) 
LSM:Register("font", "BMmini", [[Interface\Addons\SharedMedia_MyMedia\font\BMmini.TTF]]) 
LSM:Register("font", "BMplain", [[Interface\Addons\SharedMedia_MyMedia\font\BMplain.TTF]]) 
LSM:Register("font", "BMSLA___", [[Interface\Addons\SharedMedia_MyMedia\font\BMSLA___.TTF]]) 
LSM:Register("font", "boombox", [[Interface\Addons\SharedMedia_MyMedia\font\boombox.ttf]]) 
LSM:Register("font", "Borgnine", [[Interface\Addons\SharedMedia_MyMedia\font\Borgnine.ttf]]) 
LSM:Register("font", "Bumrush", [[Interface\Addons\SharedMedia_MyMedia\font\Bumrush.ttf]]) 
LSM:Register("font", "CAIPIRINHA", [[Interface\Addons\SharedMedia_MyMedia\font\CAIPIRINHA.ttf]]) 
LSM:Register("font", "CharriotDeluxe", [[Interface\Addons\SharedMedia_MyMedia\font\CharriotDeluxe.ttf]]) 
LSM:Register("font", "Comfortaa Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Comfortaa Bold.ttf]]) 
LSM:Register("font", "Comfortaa Regular", [[Interface\Addons\SharedMedia_MyMedia\font\Comfortaa Regular.ttf]]) 
LSM:Register("font", "Comfortaa Thin", [[Interface\Addons\SharedMedia_MyMedia\font\Comfortaa Thin.ttf]]) 
LSM:Register("font", "CWEBL", [[Interface\Addons\SharedMedia_MyMedia\font\CWEBL.TTF]]) 
LSM:Register("font", "CWEBS", [[Interface\Addons\SharedMedia_MyMedia\font\CWEBS.TTF]]) 
LSM:Register("font", "Decker", [[Interface\Addons\SharedMedia_MyMedia\font\Decker.ttf]]) 
LSM:Register("font", "DeckerB", [[Interface\Addons\SharedMedia_MyMedia\font\DeckerB.ttf]]) 
LSM:Register("font", "digitalfun", [[Interface\Addons\SharedMedia_MyMedia\font\digitalfun.ttf]]) 
LSM:Register("font", "DSNarXC", [[Interface\Addons\SharedMedia_MyMedia\font\DSNarXC.ttf]]) 
LSM:Register("font", "Elbaris", [[Interface\Addons\SharedMedia_MyMedia\font\Elbaris.ttf]]) 
LSM:Register("font", "ELECN___", [[Interface\Addons\SharedMedia_MyMedia\font\ELECN___.TTF]]) 
LSM:Register("font", "Emblem", [[Interface\Addons\SharedMedia_MyMedia\font\Emblem.ttf]]) 
LSM:Register("font", "Enigma", [[Interface\Addons\SharedMedia_MyMedia\font\Enigma.ttf]]) 
LSM:Register("font", "Enigma__2", [[Interface\Addons\SharedMedia_MyMedia\font\Enigma__2.ttf]]) 
LSM:Register("font", "Ernest", [[Interface\Addons\SharedMedia_MyMedia\font\Ernest.ttf]]) 
LSM:Register("font", "EURAN___", [[Interface\Addons\SharedMedia_MyMedia\font\EURAN___.TTF]]) 
LSM:Register("font", "featured", [[Interface\Addons\SharedMedia_MyMedia\font\featured.TTF]]) 
LSM:Register("font", "FRUCM___", [[Interface\Addons\SharedMedia_MyMedia\font\FRUCM___.TTF]]) 
LSM:Register("font", "FRUCRG__", [[Interface\Addons\SharedMedia_MyMedia\font\FRUCRG__.TTF]]) 
LSM:Register("font", "FRUCS___", [[Interface\Addons\SharedMedia_MyMedia\font\FRUCS___.TTF]]) 
LSM:Register("font", "Futura LT Book", [[Interface\Addons\SharedMedia_MyMedia\font\Futura LT Book.ttf]]) 
LSM:Register("font", "Futura LT Condensed Light", [[Interface\Addons\SharedMedia_MyMedia\font\Futura LT Condensed Light.ttf]]) 
LSM:Register("font", "Futura LT Heavy", [[Interface\Addons\SharedMedia_MyMedia\font\Futura LT Heavy.ttf]]) 
LSM:Register("font", "FuturaMediumBT", [[Interface\Addons\SharedMedia_MyMedia\font\FuturaMediumBT.ttf]]) 
LSM:Register("font", "gaming_channelf", [[Interface\Addons\SharedMedia_MyMedia\font\gaming_channelf.ttf]]) 
LSM:Register("font", "gnuolane", [[Interface\Addons\SharedMedia_MyMedia\font\gnuolane.ttf]]) 
LSM:Register("font", "GRUDBLIT", [[Interface\Addons\SharedMedia_MyMedia\font\GRUDBLIT.TTF]]) 
LSM:Register("font", "Helvetica LT 45 Light", [[Interface\Addons\SharedMedia_MyMedia\font\Helvetica LT 45 Light.ttf]]) 
LSM:Register("font", "Helvetica LT 55 Roman", [[Interface\Addons\SharedMedia_MyMedia\font\Helvetica LT 55 Roman.ttf]]) 
LSM:Register("font", "Helvetica LT 67 Medium Condensed", [[Interface\Addons\SharedMedia_MyMedia\font\Helvetica LT 67 Medium Condensed.ttf]]) 
LSM:Register("font", "HISCORE", [[Interface\Addons\SharedMedia_MyMedia\font\HISCORE.ttf]]) 
LSM:Register("font", "hmn521", [[Interface\Addons\SharedMedia_MyMedia\font\hmn521.ttf]]) 
LSM:Register("font", "Hooge0553", [[Interface\Addons\SharedMedia_MyMedia\font\Hooge0553.ttf]]) 
LSM:Register("font", "Hooge0555", [[Interface\Addons\SharedMedia_MyMedia\font\Hooge0555.ttf]]) 
LSM:Register("font", "Hooge0556", [[Interface\Addons\SharedMedia_MyMedia\font\Hooge0556.ttf]]) 
LSM:Register("font", "HUM521N", [[Interface\Addons\SharedMedia_MyMedia\font\HUM521N.TTF]]) 
LSM:Register("font", "Hum521Rm", [[Interface\Addons\SharedMedia_MyMedia\font\Hum521Rm.ttf]]) 
LSM:Register("font", "InstitutionRegular", [[Interface\Addons\SharedMedia_MyMedia\font\InstitutionRegular.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Bold", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Bold.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Book", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Book.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Condensed Bold", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Condensed Bold.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Condensed Book", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Condensed Book.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Condensed Demi", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Condensed Demi.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Condensed Medium", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Condensed Medium.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Demi", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Demi.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Extra Light", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Extra Light.ttf]]) 
LSM:Register("font", "ITC Avant Garde Gothic LT Medium", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Avant Garde Gothic LT Medium.ttf]]) 
LSM:Register("font", "ITC Franklin Gothic LT Book", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Franklin Gothic LT Book.ttf]]) 
LSM:Register("font", "ITC Franklin Gothic LT Demi", [[Interface\Addons\SharedMedia_MyMedia\font\ITC Franklin Gothic LT Demi.ttf]]) 
LSM:Register("font", "JOEBRG__", [[Interface\Addons\SharedMedia_MyMedia\font\JOEBRG__.TTF]]) 
LSM:Register("font", "KRAVITZ_", [[Interface\Addons\SharedMedia_MyMedia\font\KRAVITZ_.TTF]]) 
LSM:Register("font", "Kroe0555caps", [[Interface\Addons\SharedMedia_MyMedia\font\Kroe0555caps.ttf]]) 
LSM:Register("font", "Kroeger0553", [[Interface\Addons\SharedMedia_MyMedia\font\Kroeger0553.ttf]]) 
LSM:Register("font", "Kroeger0555", [[Interface\Addons\SharedMedia_MyMedia\font\Kroeger0555.ttf]]) 
LSM:Register("font", "LIBEL", [[Interface\Addons\SharedMedia_MyMedia\font\LIBEL.TTF]]) 
LSM:Register("font", "m03", [[Interface\Addons\SharedMedia_MyMedia\font\m03.TTF]]) 
LSM:Register("font", "MicroBit", [[Interface\Addons\SharedMedia_MyMedia\font\MicroBit.ttf]]) 
LSM:Register("font", "MicroN55", [[Interface\Addons\SharedMedia_MyMedia\font\MicroN55.ttf]]) 
LSM:Register("font", "MicroN56", [[Interface\Addons\SharedMedia_MyMedia\font\MicroN56.ttf]]) 
LSM:Register("font", "Minimum", [[Interface\Addons\SharedMedia_MyMedia\font\Minimum.TTF]]) 
LSM:Register("font", "mizufalp", [[Interface\Addons\SharedMedia_MyMedia\font\mizufalp.ttf]]) 
LSM:Register("font", "MODENINE", [[Interface\Addons\SharedMedia_MyMedia\font\MODENINE.TTF]]) 
LSM:Register("font", "Movie_Poster-Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Movie_Poster-Bold.ttf]]) 
LSM:Register("font", "MyriadSBC", [[Interface\Addons\SharedMedia_MyMedia\font\MyriadSBC.ttf]]) 
LSM:Register("font", "neon2", [[Interface\Addons\SharedMedia_MyMedia\font\neon2.ttf]]) 
LSM:Register("font", "palomino", [[Interface\Addons\SharedMedia_MyMedia\font\palomino.ttf]]) 
LSM:Register("font", "Paralucent Light", [[Interface\Addons\SharedMedia_MyMedia\font\Paralucent Light.ttf]]) 
LSM:Register("font", "Paralucent", [[Interface\Addons\SharedMedia_MyMedia\font\Paralucent.ttf]]) 
LSM:Register("font", "Paskowy", [[Interface\Addons\SharedMedia_MyMedia\font\Paskowy.ttf]]) 
LSM:Register("font", "Pfneutron", [[Interface\Addons\SharedMedia_MyMedia\font\Pfneutron.ttf]]) 
LSM:Register("font", "pf_tempesta_seven", [[Interface\Addons\SharedMedia_MyMedia\font\pf_tempesta_seven.ttf]]) 
LSM:Register("font", "pf_tempesta_seven_compressed", [[Interface\Addons\SharedMedia_MyMedia\font\pf_tempesta_seven_compressed.ttf]]) 
LSM:Register("font", "pf_tempesta_seven_condensed", [[Interface\Addons\SharedMedia_MyMedia\font\pf_tempesta_seven_condensed.ttf]]) 
LSM:Register("font", "PilsenPlakatRegular", [[Interface\Addons\SharedMedia_MyMedia\font\PilsenPlakatRegular.ttf]]) 
LSM:Register("font", "Pixel", [[Interface\Addons\SharedMedia_MyMedia\font\Pixel.ttf]]) 
LSM:Register("font", "Pixelation", [[Interface\Addons\SharedMedia_MyMedia\font\Pixelation.ttf]]) 
LSM:Register("font", "PixelClassic", [[Interface\Addons\SharedMedia_MyMedia\font\PixelClassic.ttf]]) 
LSM:Register("font", "pixeldeb", [[Interface\Addons\SharedMedia_MyMedia\font\pixeldeb.ttf]]) 
LSM:Register("font", "pixeldu", [[Interface\Addons\SharedMedia_MyMedia\font\pixeldu.ttf]]) 
LSM:Register("font", "pixeldub", [[Interface\Addons\SharedMedia_MyMedia\font\pixeldub.ttf]]) 
LSM:Register("font", "pixeldue", [[Interface\Addons\SharedMedia_MyMedia\font\pixeldue.ttf]]) 
LSM:Register("font", "pixelsix14", [[Interface\Addons\SharedMedia_MyMedia\font\pixelsix14.ttf]]) 
LSM:Register("font", "PLANE___", [[Interface\Addons\SharedMedia_MyMedia\font\PLANE___.TTF]]) 
LSM:Register("font", "Porky", [[Interface\Addons\SharedMedia_MyMedia\font\Porky.ttf]]) 
LSM:Register("font", "Prozak", [[Interface\Addons\SharedMedia_MyMedia\font\Prozak.ttf]]) 
LSM:Register("font", "ProzakBold", [[Interface\Addons\SharedMedia_MyMedia\font\ProzakBold.ttf]]) 
LSM:Register("font", "ps2", [[Interface\Addons\SharedMedia_MyMedia\font\ps2.TTF]]) 
LSM:Register("font", "ptarmci_", [[Interface\Addons\SharedMedia_MyMedia\font\ptarmci_.ttf]]) 
LSM:Register("font", "ptarmc__", [[Interface\Addons\SharedMedia_MyMedia\font\ptarmc__.ttf]]) 
LSM:Register("font", "ptarmi__", [[Interface\Addons\SharedMedia_MyMedia\font\ptarmi__.ttf]]) 
LSM:Register("font", "ptarm___", [[Interface\Addons\SharedMedia_MyMedia\font\ptarm___.ttf]]) 
LSM:Register("font", "pzim3x5", [[Interface\Addons\SharedMedia_MyMedia\font\pzim3x5.ttf]]) 
LSM:Register("font", "qhyts___", [[Interface\Addons\SharedMedia_MyMedia\font\qhyts___.ttf]]) 
LSM:Register("font", "Raind___", [[Interface\Addons\SharedMedia_MyMedia\font\Raind___.TTF]]) 
LSM:Register("font", "rm_midse", [[Interface\Addons\SharedMedia_MyMedia\font\rm_midse.ttf]]) 
LSM:Register("font", "rprofil6", [[Interface\Addons\SharedMedia_MyMedia\font\rprofil6.ttf]]) 
LSM:Register("font", "rprofil6bld", [[Interface\Addons\SharedMedia_MyMedia\font\rprofil6bld.ttf]]) 
LSM:Register("font", "SF Willamette Bold Italic", [[Interface\Addons\SharedMedia_MyMedia\font\SF Willamette Bold Italic.ttf]]) 
LSM:Register("font", "SF Willamette Bold", [[Interface\Addons\SharedMedia_MyMedia\font\SF Willamette Bold.ttf]]) 
LSM:Register("font", "SF Willamette Extended", [[Interface\Addons\SharedMedia_MyMedia\font\SF Willamette Extended.ttf]]) 
LSM:Register("font", "SF Willamette Italic", [[Interface\Addons\SharedMedia_MyMedia\font\SF Willamette Italic.ttf]]) 
LSM:Register("font", "SF Willamette", [[Interface\Addons\SharedMedia_MyMedia\font\SF Willamette.ttf]]) 
LSM:Register("font", "SFIntermosaicB", [[Interface\Addons\SharedMedia_MyMedia\font\SFIntermosaicB.ttf]]) 
LSM:Register("font", "SG04", [[Interface\Addons\SharedMedia_MyMedia\font\SG04.ttf]]) 
LSM:Register("font", "ShareRegular", [[Interface\Addons\SharedMedia_MyMedia\font\ShareRegular.ttf]]) 
LSM:Register("font", "SKA", [[Interface\Addons\SharedMedia_MyMedia\font\SKA.TTF]]) 
LSM:Register("font", "SKACubic01", [[Interface\Addons\SharedMedia_MyMedia\font\SKACubic01.TTF]]) 
LSM:Register("font", "Skinny", [[Interface\Addons\SharedMedia_MyMedia\font\Skinny.ttf]]) 
LSM:Register("font", "SOULPAPA", [[Interface\Addons\SharedMedia_MyMedia\font\SOULPAPA.TTF]]) 
LSM:Register("font", "speculo", [[Interface\Addons\SharedMedia_MyMedia\font\speculo.ttf]]) 
LSM:Register("font", "speculum", [[Interface\Addons\SharedMedia_MyMedia\font\speculum.ttf]]) 
LSM:Register("font", "Spyro", [[Interface\Addons\SharedMedia_MyMedia\font\Spyro.ttf]]) 
LSM:Register("font", "squaredance00", [[Interface\Addons\SharedMedia_MyMedia\font\squaredance00.ttf]]) 
LSM:Register("font", "squaredance10", [[Interface\Addons\SharedMedia_MyMedia\font\squaredance10.ttf]]) 
LSM:Register("font", "standard07_55", [[Interface\Addons\SharedMedia_MyMedia\font\standard07_55.ttf]]) 
LSM:Register("font", "SteelFish", [[Interface\Addons\SharedMedia_MyMedia\font\SteelFish.ttf]]) 
LSM:Register("font", "Straightline", [[Interface\Addons\SharedMedia_MyMedia\font\Straightline.ttf]]) 
LSM:Register("font", "StrokeyBacon", [[Interface\Addons\SharedMedia_MyMedia\font\StrokeyBacon.TTF]]) 
LSM:Register("font", "SUBAI___", [[Interface\Addons\SharedMedia_MyMedia\font\SUBAI___.TTF]]) 
LSM:Register("font", "SUBARG__", [[Interface\Addons\SharedMedia_MyMedia\font\SUBARG__.TTF]]) 
LSM:Register("font", "Swiss 721 Light BT", [[Interface\Addons\SharedMedia_MyMedia\font\Swiss 721 Light BT.ttf]]) 
LSM:Register("font", "Swiss 721 Thin BT", [[Interface\Addons\SharedMedia_MyMedia\font\Swiss 721 Thin BT.ttf]]) 
LSM:Register("font", "Tangerin", [[Interface\Addons\SharedMedia_MyMedia\font\Tangerin.ttf]]) 
LSM:Register("font", "Tangerine", [[Interface\Addons\SharedMedia_MyMedia\font\Tangerine.ttf]]) 
LSM:Register("font", "technicality", [[Interface\Addons\SharedMedia_MyMedia\font\technicality.ttf]]) 
LSM:Register("font", "Tempesta Seven Condensed", [[Interface\Addons\SharedMedia_MyMedia\font\Tempesta Seven Condensed.ttf]]) 
LSM:Register("font", "Tempesta5", [[Interface\Addons\SharedMedia_MyMedia\font\Tempesta5.ttf]]) 
LSM:Register("font", "TempestaComp", [[Interface\Addons\SharedMedia_MyMedia\font\TempestaComp.ttf]]) 
LSM:Register("font", "TempestaCond", [[Interface\Addons\SharedMedia_MyMedia\font\TempestaCond.ttf]]) 
LSM:Register("font", "TempestaReg", [[Interface\Addons\SharedMedia_MyMedia\font\TempestaReg.ttf]]) 
LSM:Register("font", "TinDog", [[Interface\Addons\SharedMedia_MyMedia\font\TinDog.ttf]]) 
LSM:Register("font", "Trade Gothic LT Bold Condensed No. 20", [[Interface\Addons\SharedMedia_MyMedia\font\Trade Gothic LT Bold Condensed No. 20.ttf]]) 
LSM:Register("font", "Trade Gothic LT", [[Interface\Addons\SharedMedia_MyMedia\font\Trade Gothic LT.ttf]]) 
LSM:Register("font", "trans___", [[Interface\Addons\SharedMedia_MyMedia\font\trans___.ttf]]) 
LSM:Register("font", "tukz", [[Interface\Addons\SharedMedia_MyMedia\font\tukz.ttf]]) 
LSM:Register("font", "Tw_Cen_MT_Bold", [[Interface\Addons\SharedMedia_MyMedia\font\Tw_Cen_MT_Bold.ttf]]) 
LSM:Register("font", "Ultima_Campagnoli", [[Interface\Addons\SharedMedia_MyMedia\font\Ultima_Campagnoli.ttf]]) 
LSM:Register("font", "unborneditrion", [[Interface\Addons\SharedMedia_MyMedia\font\unborneditrion.ttf]]) 
LSM:Register("font", "Uni", [[Interface\Addons\SharedMedia_MyMedia\font\Uni.ttf]]) 
LSM:Register("font", "Uni2", [[Interface\Addons\SharedMedia_MyMedia\font\Uni2.ttf]]) 
LSM:Register("font", "UnicumBold", [[Interface\Addons\SharedMedia_MyMedia\font\UnicumBold.TTF]]) 
LSM:Register("font", "unlearn2", [[Interface\Addons\SharedMedia_MyMedia\font\unlearn2.ttf]]) 
LSM:Register("font", "unlearne", [[Interface\Addons\SharedMedia_MyMedia\font\unlearne.ttf]]) 
LSM:Register("font", "VeraSe", [[Interface\Addons\SharedMedia_MyMedia\font\VeraSe.ttf]]) 
LSM:Register("font", "visitor1", [[Interface\Addons\SharedMedia_MyMedia\font\visitor1.ttf]]) 
LSM:Register("font", "visitor2", [[Interface\Addons\SharedMedia_MyMedia\font\visitor2.ttf]]) 
LSM:Register("font", "weezerfont", [[Interface\Addons\SharedMedia_MyMedia\font\weezerfont.ttf]]) 
LSM:Register("font", "XPAIDERP", [[Interface\Addons\SharedMedia_MyMedia\font\XPAIDERP.TTF]]) 
LSM:Register("font", "Yellowjacket", [[Interface\Addons\SharedMedia_MyMedia\font\Yellowjacket.ttf]]) 
LSM:Register("font", "ZeroesOneRegular", [[Interface\Addons\SharedMedia_MyMedia\font\ZeroesOneRegular.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "1248876008345", [[Interface\Addons\SharedMedia_MyMedia\sound\1248876008345.jpg]]) 
LSM:Register("sound", "alert", [[Interface\Addons\SharedMedia_MyMedia\sound\alert.wav]]) 
LSM:Register("sound", "alert_23", [[Interface\Addons\SharedMedia_MyMedia\sound\alert_23.wav]]) 
LSM:Register("sound", "alert_30", [[Interface\Addons\SharedMedia_MyMedia\sound\alert_30.wav]]) 
LSM:Register("sound", "anub", [[Interface\Addons\SharedMedia_MyMedia\sound\anub.wav]]) 
LSM:Register("sound", "arcanepower", [[Interface\Addons\SharedMedia_MyMedia\sound\arcanepower.wav]]) 
LSM:Register("sound", "attention", [[Interface\Addons\SharedMedia_MyMedia\sound\attention.wav]]) 
LSM:Register("sound", "becon", [[Interface\Addons\SharedMedia_MyMedia\sound\becon.wav]]) 
LSM:Register("sound", "BF", [[Interface\Addons\SharedMedia_MyMedia\sound\BF.wav]]) 
LSM:Register("sound", "buffet", [[Interface\Addons\SharedMedia_MyMedia\sound\buffet.wav]]) 
LSM:Register("sound", "carfull", [[Interface\Addons\SharedMedia_MyMedia\sound\carfull.wav]]) 
LSM:Register("sound", "cd", [[Interface\Addons\SharedMedia_MyMedia\sound\cd.wav]]) 
LSM:Register("sound", "combustion", [[Interface\Addons\SharedMedia_MyMedia\sound\combustion.wav]]) 
LSM:Register("sound", "Cooldown", [[Interface\Addons\SharedMedia_MyMedia\sound\Cooldown.wav]]) 
LSM:Register("sound", "counterspell", [[Interface\Addons\SharedMedia_MyMedia\sound\counterspell.wav]]) 
LSM:Register("sound", "danger", [[Interface\Addons\SharedMedia_MyMedia\sound\danger.wav]]) 
LSM:Register("sound", "deepfreeze", [[Interface\Addons\SharedMedia_MyMedia\sound\deepfreeze.wav]]) 
LSM:Register("sound", "defile", [[Interface\Addons\SharedMedia_MyMedia\sound\defile.wav]]) 
LSM:Register("sound", "dispell", [[Interface\Addons\SharedMedia_MyMedia\sound\dispell.wav]]) 
LSM:Register("sound", "evo", [[Interface\Addons\SharedMedia_MyMedia\sound\evo.wav]]) 
LSM:Register("sound", "fail", [[Interface\Addons\SharedMedia_MyMedia\sound\fail.wav]]) 
LSM:Register("sound", "fof", [[Interface\Addons\SharedMedia_MyMedia\sound\fof.wav]]) 
LSM:Register("sound", "GM_ChatWarning", [[Interface\Addons\SharedMedia_MyMedia\sound\GM_ChatWarning.wav]]) 
LSM:Register("sound", "goo", [[Interface\Addons\SharedMedia_MyMedia\sound\goo.sfk]]) 
LSM:Register("sound", "goo", [[Interface\Addons\SharedMedia_MyMedia\sound\goo.wav]]) 
LSM:Register("sound", "hfb", [[Interface\Addons\SharedMedia_MyMedia\sound\hfb.wav]]) 
LSM:Register("sound", "HS", [[Interface\Addons\SharedMedia_MyMedia\sound\HS.wav]]) 
LSM:Register("sound", "iceyveins", [[Interface\Addons\SharedMedia_MyMedia\sound\iceyveins.wav]]) 
LSM:Register("sound", "impact", [[Interface\Addons\SharedMedia_MyMedia\sound\impact.wav]]) 
LSM:Register("sound", "judge", [[Interface\Addons\SharedMedia_MyMedia\sound\judge.wav]]) 
LSM:Register("sound", "LB", [[Interface\Addons\SharedMedia_MyMedia\sound\LB.wav]]) 
LSM:Register("sound", "lightning", [[Interface\Addons\SharedMedia_MyMedia\sound\lightning.wav]]) 
LSM:Register("sound", "LowHP", [[Interface\Addons\SharedMedia_MyMedia\sound\LowHP.wav]]) 
LSM:Register("sound", "Lowmana", [[Interface\Addons\SharedMedia_MyMedia\sound\Lowmana.wav]]) 
LSM:Register("sound", "Mana", [[Interface\Addons\SharedMedia_MyMedia\sound\Mana.wav]]) 
LSM:Register("sound", "MI Exp", [[Interface\Addons\SharedMedia_MyMedia\sound\MI Exp.wav]]) 
LSM:Register("sound", "MI", [[Interface\Addons\SharedMedia_MyMedia\sound\MI.wav]]) 
LSM:Register("sound", "Missle Barr", [[Interface\Addons\SharedMedia_MyMedia\sound\Missle Barr.wav]]) 
LSM:Register("sound", "now", [[Interface\Addons\SharedMedia_MyMedia\sound\now.wav]]) 
LSM:Register("sound", "pc", [[Interface\Addons\SharedMedia_MyMedia\sound\pc.wav]]) 
LSM:Register("sound", "pom", [[Interface\Addons\SharedMedia_MyMedia\sound\pom.wav]]) 
LSM:Register("sound", "rup", [[Interface\Addons\SharedMedia_MyMedia\sound\rup.wav]]) 
LSM:Register("sound", "scorch exp", [[Interface\Addons\SharedMedia_MyMedia\sound\scorch exp.wav]]) 
LSM:Register("sound", "scorch", [[Interface\Addons\SharedMedia_MyMedia\sound\scorch.wav]]) 
LSM:Register("sound", "shadow beacins", [[Interface\Addons\SharedMedia_MyMedia\sound\shadow beacins.wav]]) 
LSM:Register("sound", "sheep", [[Interface\Addons\SharedMedia_MyMedia\sound\sheep.wav]]) 
LSM:Register("sound", "slice", [[Interface\Addons\SharedMedia_MyMedia\sound\slice.wav]]) 
LSM:Register("sound", "spell missed", [[Interface\Addons\SharedMedia_MyMedia\sound\spell missed.wav]]) 
LSM:Register("sound", "spell Steal", [[Interface\Addons\SharedMedia_MyMedia\sound\spell Steal.wav]]) 
LSM:Register("sound", "squire_horn_aa", [[Interface\Addons\SharedMedia_MyMedia\sound\squire_horn_aa.wav]]) 
LSM:Register("sound", "squire_horn_bb", [[Interface\Addons\SharedMedia_MyMedia\sound\squire_horn_bb.wav]]) 
LSM:Register("sound", "ss", [[Interface\Addons\SharedMedia_MyMedia\sound\ss.wav]]) 
LSM:Register("sound", "Threat", [[Interface\Addons\SharedMedia_MyMedia\sound\Threat.wav]]) 
LSM:Register("sound", "trinket", [[Interface\Addons\SharedMedia_MyMedia\sound\trinket.wav]]) 
LSM:Register("sound", "warning", [[Interface\Addons\SharedMedia_MyMedia\sound\warning.wav]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "Aluminium", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Aluminium.tga]]) 
LSM:Register("statusbar", "Armory", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Armory.tga]]) 
LSM:Register("statusbar", "BantoBar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\BantoBar.tga]]) 
LSM:Register("statusbar", "Button", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Button.tga]]) 
LSM:Register("statusbar", "cabaret1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\cabaret1.tga]]) 
LSM:Register("statusbar", "cabaret2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\cabaret2.tga]]) 
LSM:Register("statusbar", "cabaret3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\cabaret3.tga]]) 
LSM:Register("statusbar", "cabaret4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\cabaret4.tga]]) 
LSM:Register("statusbar", "cabaret5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\cabaret5.tga]]) 
LSM:Register("statusbar", "Charcoal", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Charcoal.tga]]) 
LSM:Register("statusbar", "Chisel", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Chisel.tga]]) 
LSM:Register("statusbar", "Chrome", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Chrome.tga]]) 
LSM:Register("statusbar", "Cilo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Cilo.tga]]) 
LSM:Register("statusbar", "CleanPlatesBar", [[Interface\Addons\SharedMedia_MyMedia\statusbar\CleanPlatesBar.tga]]) 
LSM:Register("statusbar", "Cloud", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Cloud.tga]]) 
LSM:Register("statusbar", "DarkBottom", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DarkBottom.tga]]) 
LSM:Register("statusbar", "DsmB1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB1.tga]]) 
LSM:Register("statusbar", "DsmB2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB2.tga]]) 
LSM:Register("statusbar", "DsmB3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB3.tga]]) 
LSM:Register("statusbar", "DsmB4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB4.tga]]) 
LSM:Register("statusbar", "DsmB5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB5.tga]]) 
LSM:Register("statusbar", "DsmB6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB6.tga]]) 
LSM:Register("statusbar", "DsmB7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB7.tga]]) 
LSM:Register("statusbar", "DsmB8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB8.tga]]) 
LSM:Register("statusbar", "DsmB9", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmB9.tga]]) 
LSM:Register("statusbar", "dsmbg1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\dsmbg1.tga]]) 
LSM:Register("statusbar", "dsmbg2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\dsmbg2.tga]]) 
LSM:Register("statusbar", "dsmbg3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\dsmbg3.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV1.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV2.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV3.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV4.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV5.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV6.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV7.tga]]) 
LSM:Register("statusbar", "DsmOpaqueV8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmOpaqueV8.tga]]) 
LSM:Register("statusbar", "DsmV1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV1.tga]]) 
LSM:Register("statusbar", "DsmV2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV2.tga]]) 
LSM:Register("statusbar", "DsmV3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV3.tga]]) 
LSM:Register("statusbar", "DsmV4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV4.tga]]) 
LSM:Register("statusbar", "DsmV5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV5.tga]]) 
LSM:Register("statusbar", "DsmV6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV6.tga]]) 
LSM:Register("statusbar", "DsmV7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV7.tga]]) 
LSM:Register("statusbar", "DsmV8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV8.tga]]) 
LSM:Register("statusbar", "DsmV9", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DsmV9.tga]]) 
LSM:Register("statusbar", "DukeF", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DukeF.tga]]) 
LSM:Register("statusbar", "DukeM", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DukeM.tga]]) 
LSM:Register("statusbar", "DukeN", [[Interface\Addons\SharedMedia_MyMedia\statusbar\DukeN.tga]]) 
LSM:Register("statusbar", "Empty", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Empty.tga]]) 
LSM:Register("statusbar", "fade1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\fade1.tga]]) 
LSM:Register("statusbar", "fade2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\fade2.tga]]) 
LSM:Register("statusbar", "Falumn", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Falumn.tga]]) 
LSM:Register("statusbar", "Flat", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Flat.tga]]) 
LSM:Register("statusbar", "Glamour", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour.tga]]) 
LSM:Register("statusbar", "Glamour1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour1.tga]]) 
LSM:Register("statusbar", "Glamour2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour2.tga]]) 
LSM:Register("statusbar", "glamour3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\glamour3.tga]]) 
LSM:Register("statusbar", "Glamour4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour4.tga]]) 
LSM:Register("statusbar", "Glamour5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour5.tga]]) 
LSM:Register("statusbar", "Glamour6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour6.tga]]) 
LSM:Register("statusbar", "Glamour7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glamour7.tga]]) 
LSM:Register("statusbar", "Glass", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Glass.tga]]) 
LSM:Register("statusbar", "Gloss", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Gloss.tga]]) 
LSM:Register("statusbar", "Graphite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Graphite.tga]]) 
LSM:Register("statusbar", "HalA", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalA.tga]]) 
LSM:Register("statusbar", "HalB", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalB.tga]]) 
LSM:Register("statusbar", "HalBackground", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalBackground.tga]]) 
LSM:Register("statusbar", "HalBackgroundA", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalBackgroundA.tga]]) 
LSM:Register("statusbar", "HalC", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalC.tga]]) 
LSM:Register("statusbar", "HalD", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalD.tga]]) 
LSM:Register("statusbar", "HalE", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalE.tga]]) 
LSM:Register("statusbar", "HalF", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalF.tga]]) 
LSM:Register("statusbar", "HalG", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalG.tga]]) 
LSM:Register("statusbar", "HalGla", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalGla.tga]]) 
LSM:Register("statusbar", "HalH", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalH.tga]]) 
LSM:Register("statusbar", "HalI", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalI.tga]]) 
LSM:Register("statusbar", "HalJ", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalJ.tga]]) 
LSM:Register("statusbar", "HalK", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalK.tga]]) 
LSM:Register("statusbar", "HalL", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalL.tga]]) 
LSM:Register("statusbar", "HalM", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalM.tga]]) 
LSM:Register("statusbar", "HalN", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalN.tga]]) 
LSM:Register("statusbar", "HalO", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalO.tga]]) 
LSM:Register("statusbar", "HalP", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalP.tga]]) 
LSM:Register("statusbar", "HalQ", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalQ.tga]]) 
LSM:Register("statusbar", "HalR", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalR.tga]]) 
LSM:Register("statusbar", "HalS", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalS.tga]]) 
LSM:Register("statusbar", "HalT", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalT.tga]]) 
LSM:Register("statusbar", "HalU", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalU.tga]]) 
LSM:Register("statusbar", "HalV", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalV.tga]]) 
LSM:Register("statusbar", "HalW", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalW.tga]]) 
LSM:Register("statusbar", "HalX", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalX.tga]]) 
LSM:Register("statusbar", "Ish00", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ish00.tga]]) 
LSM:Register("statusbar", "Ish04", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ish04.tga]]) 
LSM:Register("statusbar", "Ish05", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ish05.tga]]) 
LSM:Register("statusbar", "Ish_C", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ish_C.tga]]) 
LSM:Register("statusbar", "Ish_D", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ish_D.tga]]) 
LSM:Register("statusbar", "Melli", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Melli.tga]]) 
LSM:Register("statusbar", "MelliDark", [[Interface\Addons\SharedMedia_MyMedia\statusbar\MelliDark.tga]]) 
LSM:Register("statusbar", "Metz", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Metz.tga]]) 
LSM:Register("statusbar", "Minimalist", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Minimalist.tga]]) 
LSM:Register("statusbar", "Otravi", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Otravi.tga]]) 
LSM:Register("statusbar", "Ruben", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Ruben.tga]]) 
LSM:Register("statusbar", "savant1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant1.tga]]) 
LSM:Register("statusbar", "savant2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant2.tga]]) 
LSM:Register("statusbar", "savant3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant3.tga]]) 
LSM:Register("statusbar", "savant4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant4.tga]]) 
LSM:Register("statusbar", "savant5", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant5.tga]]) 
LSM:Register("statusbar", "savant6", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant6.tga]]) 
LSM:Register("statusbar", "savant7", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant7.tga]]) 
LSM:Register("statusbar", "savant8", [[Interface\Addons\SharedMedia_MyMedia\statusbar\savant8.tga]]) 
LSM:Register("statusbar", "Smooth", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smooth.tga]]) 
LSM:Register("statusbar", "Smoothv2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smoothv2.tga]]) 
LSM:Register("statusbar", "Smudge", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Smudge.tga]]) 
LSM:Register("statusbar", "StripeBorder", [[Interface\Addons\SharedMedia_MyMedia\statusbar\StripeBorder.tga]]) 
LSM:Register("statusbar", "Striped", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Striped.tga]]) 
LSM:Register("statusbar", "StripeNoBorder", [[Interface\Addons\SharedMedia_MyMedia\statusbar\StripeNoBorder.tga]]) 
LSM:Register("statusbar", "tap1", [[Interface\Addons\SharedMedia_MyMedia\statusbar\tap1.tga]]) 
LSM:Register("statusbar", "tap2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\tap2.tga]]) 
LSM:Register("statusbar", "tap3", [[Interface\Addons\SharedMedia_MyMedia\statusbar\tap3.tga]]) 
LSM:Register("statusbar", "tap4", [[Interface\Addons\SharedMedia_MyMedia\statusbar\tap4.tga]]) 
LSM:Register("statusbar", "Wglass", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Wglass.tga]]) 
